#! /bin/bash

# retrieve accession numbers from blast results
for i in ./blastout/*blastout
do
  echo "getting hit accessions  $i ..."
  cut -f2 $i > ${i%.}_hits
done

# all accession files sent to new dir called hit1_accession
mkdir hit1_accessions

mv ./blastout/*hits ./hit1_accessions
