#! /bin/bash

# This script must be run in the same dir as where phylip files are located 

for phylip in *phylip
do
    raxmlHPC-PTHREADS -T 15 -s $phylip -m PROTGAMMALGF -p 12345 -n ${phylip%._}.tre
done

mkdir RAx_out
mv RAxML* RAx_out
